# Generated by Django 4.1.3 on 2023-08-02 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('other', '0002_alter_course_options_alter_dayname_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('profession', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='other.profession')),
                ('student', models.ForeignKey(limit_choices_to={'is_active': True, 'is_student': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "O'quvchilar",
                'verbose_name_plural': "O'quvchilar",
            },
        ),
    ]
