# Generated by Django 4.1.3 on 2023-08-02 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Qayerdan kelgan',
                'verbose_name_plural': '2.0 Qayerdan kelgan',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=221, verbose_name='Nomi')),
                ('duration', models.IntegerField(verbose_name='Kurs davomiligi /soati')),
                ('payment', models.FloatField(verbose_name='Tolov')),
                ('lesson_duration', models.IntegerField(verbose_name='Dars davomligi /soati')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kurslar',
                'verbose_name_plural': '1. Kurslar',
            },
        ),
        migrations.CreateModel(
            name='DayName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Kunlar',
                'verbose_name_plural': '5. Kunlar',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Nomi')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Yo'nalishlar",
                'verbose_name_plural': "3. Yo'nalishlar",
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Xona')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Xonalar',
                'verbose_name_plural': '4. Xonalar',
            },
        ),
        migrations.CreateModel(
            name='WhereCome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('advertising', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='other.advertising')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='where_come', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Qayerdan kelgan',
                'verbose_name_plural': '2.1 Qayerdan kelgan',
            },
        ),
    ]
