# Generated by Django 4.1.3 on 2023-08-02 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('other', '0002_alter_course_options_alter_dayname_options_and_more'),
        ('student', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=221, verbose_name='Guruh Nomi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='GroupImages/', verbose_name='Gruh Logotipi')),
                ('is_active', models.BooleanField(default=True)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_day', to='other.dayname')),
                ('direction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_direction', to='other.profession', verbose_name='Yonalish')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_room', to='other.room', verbose_name='Xona')),
                ('students', models.ManyToManyField(related_name='group_students', to='student.student', verbose_name='Talaba')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_teacher', to='teacher.teacher', verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': '4. Guruhlar',
                'verbose_name_plural': 'Guruhlar',
            },
        ),
    ]
